accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views #this as is just to change name and not mess up the import views below
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
]

posts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    re_path('by/(?P<username>[-\w]+)/', views.UserPosts.as_view(), name='for_user'),
    re_path('by/(?P<username>[-\w]+)/(?P<pk>[-\w]+)/', views.PostDetail.as_view(), name='single'),
    path('delete/(?P<pk>[-\w]+)/', views.DeletePost.as_view(), name='delete'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Homepage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Star Social</title>

    <!-- CSS only -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Muli:wght@200;500;900&family=Oswald:wght@200;400;700&display=swap" rel="stylesheet">
</head>

<body>

    <!-- NAVBAR -->
    <nav class="mynav navbar navbar-expand-lg navbar-light bg-light" role='navigation' id='navbar'>
        <div class='container'>
            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
            <ul class='nav ml-auto'>
                {% if user.is_authenticated %}
                    <li><a class="nav-item nav-link" href="{% url 'posts:create' %}">Post</a></li>
                    <li><a class="nav-item nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a class="nav-item nav-link" href="{% url 'groups:create' %}">Create Group</a></li>
                    <li><a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="nav-item nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mycontent">
        
        {% block content %}
        {% endblock  %}
        
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1><a href="{% url 'posts:all' %}">{{user.username}}
</a>welcome to our home page!</h1>

{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
<h1>you are now loggedin</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
<h1>thanks for visiting</h1>
{% endblock %}